<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="DinkToPdf" Version="1.0.7" />
    <PackageReference Include="EPPlus" Version="8.0.8" />
    <PackageReference Include="Newtonsoft.Json" Version="13.0.3" />
    <PackageReference Include="PuppeteerSharp" Version="10.1.0" />
    <PackageReference Include="QRCoder" Version="1.6.0" />
    <PackageReference Include="SixLabors.ImageSharp" Version="3.1.11" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\..\Repositories\MainModels\MainModels\MainModels.csproj" />
  </ItemGroup>

</Project>
