<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.SignalR" Version="1.2.0" />
    <PackageReference Include="Microsoft.AspNetCore.SignalR.Client" Version="9.0.7" />
    <PackageReference Include="Microsoft.AspNetCore.SignalR.Common" Version="9.0.7" />
    <PackageReference Include="Microsoft.AspNetCore.SignalR.Core" Version="1.2.0" />
    <PackageReference Include="Microsoft.VisualStudio.Web.CodeGeneration.Design" Version="9.0.0" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Areas\Account\Data\" />
    <Folder Include="Areas\Account\Models\" />
    <Folder Include="Areas\AdminArea\Data\" />
    <Folder Include="Areas\AdminArea\Models\" />
    <Folder Include="Areas\Notification\Models\" />
    <Folder Include="Areas\Notification\Views\" />
    <Folder Include="Areas\Product\Data\" />
    <Folder Include="Areas\Product\Models\" />
    <Folder Include="Areas\Purchase\Data\" />
    <Folder Include="Areas\Purchase\Models\" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\..\Repositories\MainModels\MainModels\MainModels.csproj" />
    <ProjectReference Include="..\MarketBal\MarketBal.csproj" />
  </ItemGroup>

</Project>
