<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <Content Remove="Areas\AdminArea\Views\AdminPanel\StartupSettings.cshtml" />
    <Content Remove="wwwroot\chrome-win.zip" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.SignalR" Version="1.2.0" />
    <PackageReference Include="Microsoft.AspNetCore.SignalR.Client" Version="9.0.7" />
    <PackageReference Include="Microsoft.AspNetCore.SignalR.Common" Version="9.0.7" />
    <PackageReference Include="Microsoft.AspNetCore.SignalR.Core" Version="1.2.0" />
    <PackageReference Include="Microsoft.VisualStudio.Web.CodeGeneration.Design" Version="9.0.0" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Areas\AccountingArea\Data\" />
    <Folder Include="Areas\AccountingArea\Models\" />
    <Folder Include="Areas\Account\Data\" />
    <Folder Include="Areas\Account\Models\" />
    <Folder Include="Areas\AdminArea\Data\" />
    <Folder Include="Areas\AdminArea\Models\" />
    <Folder Include="Areas\Collections\Data\" />
    <Folder Include="Areas\Collections\Models\" />
    <Folder Include="Areas\InvoiceArea\Controllers\" />
    <Folder Include="Areas\InvoiceArea\Data\" />
    <Folder Include="Areas\InvoiceArea\Models\" />
    <Folder Include="Areas\InvoiceArea\Views\" />
    <Folder Include="Areas\Notification\Models\" />
    <Folder Include="Areas\Notification\Views\" />
    <Folder Include="Areas\OrderSection\Data\" />
    <Folder Include="Areas\OrderSection\Models\" />
    <Folder Include="Areas\POS\Data\" />
    <Folder Include="Areas\POS\Models\" />
    <Folder Include="Areas\Product\Data\" />
    <Folder Include="Areas\Product\Models\" />
    <Folder Include="Areas\Purchase\Data\" />
    <Folder Include="Areas\Purchase\Models\" />
  </ItemGroup>

  <ItemGroup>
    <None Include=".github\workflows\dotnet-ci-cd.yml" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\..\Repositories\MainModels\MainModels\MainModels.csproj" />
    <ProjectReference Include="..\MarketBal\MarketBal.csproj" />
  </ItemGroup>

  <ItemGroup>
    <None Update="libwkhtmltox.dll">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
  </ItemGroup>

</Project>
